### ISSUE TITLE
Expiration date is ignored in Chrome

### ISSUE THREAD

**Issue by EwaOlch** [BitzArt/Blazor.Cookies#18]
In the Chrome browser, the Expiration date is ignored and the cookie is set as a Session cookie instead.

It may be because MaxAge is missing from the configuration?

**Comment by YuriyDurov** [comment]
I have just checked by setting a cookie in both static and interactive rendering - does not seem like this is the case for either of them.

We are going to need additional information in order to be able to investigate this further. An example solution where this can be replicated would be nice.

Also, consider checking the [sample app](https://github.com/BitzArt/Blazor.Cookies/tree/main/sample/BitzArt.Blazor.Cookies.SampleApp) for an implementation reference.

**Comment by YuriyDurov** [comment]
Closing due to a lack of activity.
